# Simple docker-compose.yml

version: '3.3'

services:
  notymail:
    image: dafnik/notymail:latest
    container_name: notymail
    ports:
      - 3124:3124 # <Host Port>:<Container Port>
    restart: always
    environment:
      API_KEYS:
      MAIL_SENDER: notymail <test@1.1.1.1>
      MAIL_HOST: gmail.com
      MAIL_PORT: 587
      MAIL_SECURE: false
      MAIL_AUTH_USER: test@1.1.1.
      MAIL_AUTH_PASSWORD: password
