name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker prod image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          target: runner
          build-args: |
            version=${{ github.ref_name }}
          # tags: 3.4.0, latest
          tags: |
            ghcr.io/notymail/core:${{ github.ref_name }}
            ghcr.io/notymail/core:latest
            dafnik/notymail:${{ github.ref_name }}
            dafnik/notymail:latest
